map_file: map.txt
graph_size:
  x: 4
  y: 4
stations: [[0, 3], [3, 3]]
UAV:
  init_state: [1, 2]
  battery: 12
clouds:
  maximal_stay_steps: 3
  positions: []
  dynamics: 'random_walk'
targets: [[0, 0],[3, 0],[2, 1]]
obstacles: []
manual: True
sample_path: [0, 0, 1, 2, 3, 1, 2, 0, 0]
rendering: False
